Fixes issue #69
- Dockerfile: Added can-utils to the image, Fixed ubuntu base version to be compatible with build version
- Fixed seat controller scripts to use /bin/sh
- Added "SC_RESET" env variable to disable running ecu-reset script from val_start.sh. Enabled by default.
- Improved sim-SECU1_STAT to support testing for ecu-reset script without hardware
- Updated relevant READMEs
- Fixed cansim dump
- Fixed ubuntu version used for building integration tests containers

Signed-off-by: Ivan Kirchev <Ivan.Kirchev@bosch.com>

diff --git a/.github/workflows/integration_test.yml b/.github/workflows/integration_test.yml
--- a/.github/workflows/integration_test.yml
+++ b/.github/workflows/integration_test.yml
@@ -25,7 +25,8 @@ on:
 
 jobs:
   integration-test:
-    runs-on: ubuntu-latest
+    # reduce runtime requirements from libc/libc++
+    runs-on: ubuntu-20.04
     # container:
     #   image: ghcr.io/${{ github.repository }}/oci_kuksa-val-services-ci:v0.1.0
     #   credentials:
@@ -78,7 +79,11 @@ jobs:
           HVAC_TAG: "prerelease"
         run: |
           ./integration_test/it-setup.sh init
-          ./integration_test/it-setup.sh start
+          if ! ./integration_test/it-setup.sh start; then
+            echo "### Container startup failed logs:"
+            ./integration_test/it-setup.sh status --logs
+            exit 1
+          fi
           sleep 1
           ./integration_test/it-setup.sh status --logs
           # echo "$ docker image ls"
